In [1]:
import os
import sys
import pandas as pd

In [2]:
crassus = pd.read_csv("crassus_results.tsv.gz", delimiter="\t", compression='gzip')
crassus

,crassus_id,contig,sample,length,length/ref,ref,DTR,coding,family,subfamily,genus,species,evidence_family,evidence_genus,notes,discard
0,IBD-crossAssembled_1_182976,contig_241570,IBD-crossAssembled,182976,0.978,Zeta_2,True,11,Zeta,Zeta,Zeta_2,species__72,"phylogenies, shared_prots","ani, shared_prots",NaN,False
1,IBD-crossAssembled_2_178222,contig_8225,IBD-crossAssembled,178222,0.975,Zeta_3_1,False,11,Zeta,Zeta,Zeta_3,Zeta_3_1,"phylogenies, shared_prots","ani, shared_prots, phylogenies",NaN,False
2,IBD-crossAssembled_4_145297,contig_1091,IBD-crossAssembled,145297,0.954,Epsilon_2_3,False,11,Epsilon,Epsilon,Epsilon_2,Epsilon_2_3,"phylogenies, shared_prots","ani, shared_prots, phylogenies",NaN,False
3,IBD-crossAssembled_7_141010,contig_1857,IBD-crossAssembled,141010,0.922,Epsilon_1,False,11,Epsilon,Epsilon,Epsilon_1,species__92,"phylogenies, shared_prots","ani, shared_prots, phylogenies",NaN,False
4,IBD-crossAssembled_16_113452,contig_17571,IBD-crossAssembled,113452,0.640,Zeta_7_1,False,TGA,Zeta,Zeta,Zeta_7,Zeta_7_1,"phylogenies, shared_prots","ani, shared_prots, phylogenies",NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,IBD-crossAssembled_3122_11376,contig_7298,IBD-crossAssembled,11376,0.118,Buorbuivirus,False,TAG,Suoliviridae,Loutivirinae,Buorbuivirus,species__173,"phylogenies, shared_prots",ani,NaN,False
107,IBD-crossAssembled_3177_11243,contig_20815,IBD-crossAssembled,11243,0.113,Kolpuevirus hominis,False,11,Steigviridae,Asinivirinae,Kolpuevirus,Kolpuevirus hominis,"phylogenies, shared_prots","ani, shared_prots, phylogenies",NaN,False
108,IBD-crossAssembled_3515_10591,contig_239060,IBD-crossAssembled,10591,0.109,Carjivirus communis,False,11,Intestiviridae,Crudevirinae,Carjivirus,Carjivirus communis,"phylogenies, shared_prots","ani, shared_prots, phylogenies",NaN,False
109,IBD-crossAssembled_3720_10264,contig_240585,IBD-crossAssembled,10264,0.112,Dabirmavirus,False,11,Intestiviridae,Crudevirinae,Dabirmavirus,species__174,"phylogenies, shared_prots",ani,NaN,False
110,IBD-crossAssembled_3833_10082,contig_241434,IBD-crossAssembled,10082,0.101,Kolpuevirus hominis,False,11,Steigviridae,Asinivirinae,Kolpuevirus,Kolpuevirus hominis,"phylogenies, shared_prots","ani, shared_prots",NaN,False

In [3]:
crassshort = crassus[['contig', 'length', 'ref', 'coding', 'family']]

In [4]:
contigs = pd.read_csv("crass_contigs.tsv.gz", delimiter="\t", compression='gzip')
contigs

,sample,contig,length,Reads,RPKM,FPKM,SPM,averageFold,referenceGC,coveragePercentage,coverageBases,medianFold
0,7544,contig_10493,18937,2,0.06,0.06,0.35,0.05,0.3441,4.18,792,0.28
1,7544,contig_1091,145297,3,0.01,0.01,0.03,0.01,0.3817,0.50,724,0.07
2,7544,contig_12034,21580,485,11.80,11.78,57.58,9.03,0.3575,85.35,18418,8.32
3,7544,contig_12041,29559,266,4.73,4.73,20.76,3.25,0.3691,66.94,19786,4.40
4,7544,contig_12042,11863,108,4.78,4.78,20.00,3.13,0.3659,64.55,7658,3.64
...,...,...,...,...,...,...,...,...,...,...,...,...
18474,38211,contig_5776,88456,6,0.03,0.03,0.11,0.02,0.3260,0.96,853,0.23
18475,38211,contig_7024,36085,6,0.08,0.08,0.22,0.04,0.3279,3.68,1328,0.23
18476,38211,contig_7034,16937,1,0.03,0.00,0.07,0.01,0.3478,1.38,234,0.12
18477,38211,contig_7054,34118,4,0.06,0.06,0.19,0.04,0.3275,2.98,1016,0.22
18478,38211,contig_7091,66998,8,0.06,0.06,0.18,0.04,0.3245,2.73,1832,0.23

In [5]:
wehave = set()
with open("freezer.txt", 'r') as f:
    for l in f:
        l = l.strip()
        if l:
            wehave.add(int(l))
wehave

{33855,
 33856,
 33857,
 33858,
 33859,
 33860,
 33861,
 33862,
 33863,
 33865,
 33866,
 33867,
 33868,
 33869,
 33870,
 33871,
 33872,
 33877,
 33878,
 33879,
 33880,
 33881,
 33882,
 33883,
 33884,
 33887,
 33888,
 33890,
 33891,
 33893,
 33895,
 33896,
 33897,
 33898,
 33901,
 33902,
 33906,
 33907,
 33908,
 33909,
 33910,
 33911,
 33913,
 33914,
 33915,
 33916,
 33917,
 33922,
 33924,
 33925,
 33926,
 33929,
 33931,
 33932,
 33936,
 33937,
 33939,
 33940,
 33941,
 33942,
 33943,
 33947,
 33949,
 33950,
 33951,
 33953,
 33954,
 33955,
 33957,
 33958,
 33959,
 33960,
 33961,
 33963,
 33964,
 33965,
 33966,
 33968,
 33969,
 33970,
 33972,
 33973,
 33974,
 33975,
 33976,
 33978,
 33979,
 33980,
 33981,
 33982,
 33983,
 33984,
 33988,
 33989,
 33991,
 33992,
 33993,
 33995,
 33996,
 33997,
 33998,
 33999,
 34000,
 34001,
 34002,
 34003,
 34006,
 34007,
 34008,
 34009,
 34010,
 34011,
 34012,
 34013,
 34015,
 34018,
 34019,
 34020,
 34022,
 34024,
 34027,
 34028,
 34029,
 34030,
 34031,
 34033,
 34035,
 34036,
 34037,
 34038,
 34039,
 34040,
 34041,
 34042,
 34043,
 34044,
 34054}

In [6]:
ourcontigs = contigs[contigs['sample'].isin(wehave)]
ourcontigs

,sample,contig,length,Reads,RPKM,FPKM,SPM,averageFold,referenceGC,coveragePercentage,coverageBases,medianFold
6294,33855,contig_10982,14547,1228,70.77,70.77,173.98,19.77,0.3652,88.46,12868,23.69
6295,33855,contig_11000,18137,350,16.18,16.18,38.78,4.41,0.3337,48.42,8782,7.67
6296,33855,contig_11002,106707,894,7.02,7.02,17.31,1.97,0.3259,23.40,24971,6.93
6297,33855,contig_11067,24409,72,2.47,2.47,5.99,0.68,0.3359,7.37,1799,3.76
6298,33855,contig_12149,59357,23686,334.53,334.53,821.66,93.36,0.3261,83.21,49392,108.36
...,...,...,...,...,...,...,...,...,...,...,...,...
9328,34044,contig_3325,29397,3,0.05,0.04,0.11,0.03,0.3057,1.07,316,0.27
9329,34044,contig_3469,56074,2448,23.24,23.24,48.45,12.08,0.3430,77.75,43600,15.53
9330,34044,contig_7091,66998,2,0.02,0.02,0.04,0.01,0.3245,0.57,380,0.13
9331,34044,contig_7377,35885,2,0.03,0.03,0.08,0.02,0.3317,1.34,480,0.18
9332,34044,contig_8225,178222,3,0.01,0.01,0.02,0.01,0.3687,0.36,646,0.09

In [7]:
ourcontshort = ourcontigs[['sample', 'contig', 'reads']]
ourcontshort

      sample        contig  Reads
6294   33855  contig_10982   1228
6295   33855  contig_11000    350
6296   33855  contig_11002    894
6297   33855  contig_11067     72
6298   33855  contig_12149  23686
...      ...           ...    ...
9328   34044   contig_3325      3
9329   34044   contig_3469   2448
9330   34044   contig_7091      2
9331   34044   contig_7377      2
9332   34044   contig_8225      3

[2159 rows x 3 columns]

In [8]:
annocont = pd.merge(ourcontshort, crassshort, on='contig')
annocont

,sample,contig,Reads,length,ref,coding,family
0,33855,contig_10982,1228,14547,Kehishuvirus,11,Steigviridae
1,33861,contig_10982,48,14547,Kehishuvirus,11,Steigviridae
2,33898,contig_10982,2,14547,Kehishuvirus,11,Steigviridae
3,33908,contig_10982,1,14547,Kehishuvirus,11,Steigviridae
4,33940,contig_10982,4,14547,Kehishuvirus,11,Steigviridae
...,...,...,...,...,...,...,...
2154,33992,contig_11554,437,30342,NaN,11,unknown
2155,33993,contig_11554,2,30342,NaN,11,unknown
2156,34000,contig_242504,319,15858,Drivevirus gastrointestinalis,11,Intestiviridae
2157,34001,contig_242504,2,15858,Drivevirus gastrointestinalis,11,Intestiviridae
2158,34011,contig_11676,8,36325,Mahstovirus,11,Steigviridae

In [9]:
annocont.to_csv("our_crassphage.tsv.gz", sep="\t", compression='gzip')

In [19]:
rdrp = pd.read_csv('rdrp_contig_count_table.tsv.gz',  sep="\t", compression='gzip')
rdrp

,sample,contig,length,reads,RPKM,FPKM,SPM,averageFold,referenceGC,coveragePercentage,coverageBases,MedianFold
0,7544,contig_102265,1524,4,1.38,1.38,5.14,0.81,0.4337,26.57,405,1.46
1,7544,contig_115141,1423,3,1.11,0.74,3.74,0.59,0.4329,42.16,600,0.76
2,7544,contig_147529,1247,4,1.68,1.68,6.54,1.02,0.4338,37.37,466,1.35
3,7544,contig_158706,1079,64,31.15,31.15,125.67,19.70,0.4217,100.00,1079,11.30
4,7544,contig_217056,1035,6,3.04,3.04,9.17,1.44,0.4415,47.92,496,1.62
...,...,...,...,...,...,...,...,...,...,...,...,...
794,38209,contig_58328,2220,25,8.09,7.77,25.07,3.48,0.4667,20.18,448,7.29
795,38210,contig_58328,2220,179,29.33,29.17,34.11,20.49,0.4667,27.75,616,42.13
796,38211,contig_121925,1378,2,0.69,0.69,2.55,0.50,0.4862,33.45,461,0.77
797,38211,contig_23429,8205,2,0.12,0.12,0.45,0.09,0.4924,6.17,506,0.37
798,38211,contig_58328,2220,1,0.22,0.00,0.53,0.11,0.4667,10.54,234,0.31

In [21]:
rdrpshort = rdrp[['sample', 'contig', 'reads']]
ourrdrp = rdrpshort[rdrpshort['sample'].isin(wehave)]
ourrdrp.to_csv("rdrp_wehave.tsv.gz",  sep="\t", compression='gzip')